[package]
name = "trigram_cos_comp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.1"
rayon = "1.10.0"
rustc-hash = "1.1.0"
textdistance = "1.0.2"
